#!/bin/bash

RAND=$RANDOM

function check {
  RESULT=$(curl localhost:8080/check \
   -s \
   -H "Content-Type: application/json" \
   -XPOST -d \
   "{ \"ip\":\"$1\",
      \"mid\":\"$2\",
      \"uid\":\"$RAND\"
    }")

  if [ "$RESULT" != "$3" ]; then
    echo "Failed. Expected: $RESULT received $3."
    exit 1
  fi

}

function add {
  RESULT=$(curl localhost:8080/add \
   -s \
   -H "Content-Type: application/json" \
   -XPOST -d \
   "{ \"ip\":\"$1\",
      \"mid\":\"$2\",
      \"uid\":\"$RAND\"
    }")

  if [ "$RESULT" != "$3" ]; then
    echo "Failed. Expected: $RESULT received $3."
    exit 1
  fi
}

function reset {
  RESULT=$(curl localhost:8080/reset \
   -s)

  if [ "$RESULT" != "$1" ]; then
    echo "Failed. Expected: $RESULT received $1."
    exit 1
  fi
}

echo Brand new user. Begin their graph.
check "1.1.1.1" "COOKIEONE" "OK"

echo Login with new computers in the same house
check "1.1.1.1" "COOKIETWO" "OK"
check "1.1.1.1" "COOKIETHREE" "OK"
check "1.1.1.1" "COOKIEFOUR" "OK"

add "5.5.5.5" "NEWCOOKIE" "ADD"

echo Login from work with laptop
check "2.2.2.2" "COOKIETWO" "OK"

echo Suspicious Login!
check "4.4.4.4" "BADCOOKIE" "BAD"

echo Bad Data!
check "<script>alert(null)>" "BADCOOKIE" "BAD"
check "2.2.2.2" "'<&2$;:" "BAD"

echo Add that previously suspicious login
add "4.4.4.4" "BADCOOKIE" "ADD"

echo Not so suspicious now, is it?
check "4.4.4.4" "BADCOOKIE" "OK"

echo Try resetting the database
reset "RESET"

echo Database reset and our data is here, persistance successful.
check "4.4.4.4" "BADCOOKIE" "OK"

echo "All tests have passed."
