#!/bin/bash

RAND=$RANDOM

function post {
  RESULT=$(curl localhost:8080/check \
   -s \
   -H "Content-Type: application/json" \
   -XPOST -d \
   "{ \"ip\":\"$1\",
      \"mid\":\"$2\",
      \"uid\":\"$RAND\"
    }")

  if [ "$RESULT" == "$3" ]
    then echo "Passed."
  else
    echo "Failed."
    exit 1
  fi

}

#Brand new user. Begin their graph.
post "1.1.1.1" "COOKIEONE" "OK"
#Login with new computers in the same house
post "1.1.1.1" "COOKIETWO" "OK"
post "1.1.1.1" "COOKIETHREE" "OK"
post "1.1.1.1" "COOKIEFOUR" "OK"

#Login from work with laptop
post "2.2.2.2" "COOKIETWO" "OK"

#Suspicious Login!
post "4.4.4.4" "BADCOOKIE" "BAD"
